#ifndef SPBSPU_LABS_2025_AADS_A_KIZHIN_EVGENIY_COMMON_INTERNAL_FORWARD_LIST_FWD_HPP
#define SPBSPU_LABS_2025_AADS_A_KIZHIN_EVGENIY_COMMON_INTERNAL_FORWARD_LIST_FWD_HPP

namespace kizhin {
  template < typename T >
  class ForwardList;
}

#endif

